import './scss/main.scss'
import './scss/catalog.scss'
import './scss/itc-slider.css'
import './modules/itc-slider'
import './modules/price_min_max'
import './modules/catalog'
import './modules/script'
